# ECR deployment next.
name: ecr_docker_deployment
on: 
  workflow_dispatch: 
jobs:
  docker_cicd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
           
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY }}
          aws-region: ap-southeast-2
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Configure Azure Credentials
        # env:
        #   AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          allow-no-subscriptions: true 
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

        # run:
        #   echo "Azure credentials are set up."
        #   echo $AZURE_CREDENTIALS > azure_credentials.json
      # - name: Print Azure Credentials (Caution:For Debugging Only)
      #   run: echo ${{ secrets.AZURE_CREDENTIALS }}

      - name: Print Tenant ID (Caution:For Debugging Only)
        run: |
          echo ${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}
          echo ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
          echo ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}

      - name: Set up Azure Credentials for Python Script
        run: |
          echo "AZURE_TENANT_ID=${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}" >> $GITHUB_ENV
          echo "AZURE_CLIENT_ID=${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}" >> $GITHUB_ENV
          echo "AZURE_CLIENT_SECRET=${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}" >> $GITHUB_ENV



      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: sample_repo
          IMAGE_TAG: ${{ github.sha }}
          
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          aws lambda update-function-code \
            --function-name github_docker_demo \
            --image-uri $REGISTRY/$REPOSITORY:$IMAGE_TAG
      
